### ISSUE TITLE
aaai 19 paper

### ISSUE THREAD

**Issue by valencebond** [wangxiao5791509/Pedestrian-Attribute-Recognition-Paper-List#2]
i notice there are two aaai19 paper in repo, you provide with google drive, but i can not find it in google scholar. can you tell me how to get it, if i want to reference in my work。

**Comment by wangxiao5791509** [comment]
@valencebond  Hi, I get these paper by sending the email to the authors. These papers can't be find in the google scholar yet, but you can write the bib files according to the regular format for these two papers. Then, you can cite them in your work.

**Comment by valencebond** [comment]
@wangxiao5791509 thanks~
