### ISSUE TITLE
RAP dataset

### ISSUE THREAD

**Issue by huangyiping-ai** [wangxiao5791509/Pedestrian-Attribute-Recognition-Paper-List#3]
Hello, can you share the RAP dataset? Thank you, 18640385797@163.com , I can't apply successfully！

**Comment by JunWangYi** [comment]
> Hello, can you share the RAP dataset? Thank you, [18640385797@163.com](mailto:18640385797@163.com) , I can't apply successfully！

Do you get the RAP dataset? I can't apply it too.If you get it ,please sent it to hzf0226@tju.edu.cn .Thank you.

**Comment by valencebond** [comment]
hi @JunWangYi  @huangyiping-ai , RAP datasets do not need to apply any more, please visit our[website](http://www.rapdataset.com/), download links are on there.

**Comment by JunWangYi** [comment]
![image](https://user-images.githubusercontent.com/48719780/88360961-12193e00-cdaa-11ea-8fb9-1d97081d2153.png)
Hello, thank you for your reply, but only the second link can be opened, other links have problems, all show error, please check the link.Thank you.

**Comment by wangxiao5791509** [comment]
I want to share these datasets, but I can't. The authors asked us not to distribute this dataset. ---- "请不要分发此数据集，也不要将其用于商业目的。谢谢。"

**Comment by JunWangYi** [comment]
> I want to share these datasets, but I can't. The authors asked us not to distribute this dataset. ---- "请不要分发此数据集，也不要将其用于商业目的。谢谢。"

谢谢你，我解决了链接打不开的问题，需要对链接进行简单修改，直接打开会出问题，虽然我也不清楚为什么
