### ISSUE TITLE
A_Strong_Baseline_of_Pedestrian_Attribute_Recognition

### ISSUE THREAD

**Issue by valencebond** [wangxiao5791509/Pedestrian-Attribute-Recognition-Paper-List#4]
Hi,  
Thanks for your list of pedestrian attribute recognition
We now release a solid and strong baseline for pedestrian attribute recognition,  https://github.com/valencebond/Strong_Baseline_of_Pedestrian_Attribute_Recognition.
Compared with performance of  state-of-the-art methods, our baseline can achieve comparable even better performance on PETA, PA100k and PARv1, RAPv2 dataset.
Can you please add it to your repo? Hope it will facilitate your research.

**Comment by wangxiao5791509** [comment]
@valencebond  Cool. No problem.
